1.Write a Python Program to Add Two Matrices?

In [2]:
rows = int(input("Enter the Number of rows : " ))
column = int(input("Enter the Number of Columns: "))

print("Enter the elements of First Matrix:")
matrix_a= [[int(input()) for i in range(column)] for i in range(rows)]
print("First Matrix is: ")
for n in matrix_a:
    print(n)

print("Enter the elements of Second Matrix:")
matrix_b= [[int(input()) for i in range(column)] for i in range(rows)]
for n in matrix_b:
    print(n)
    
result=[[0 for i in range(column)] for i in range(rows)]

for i in range(rows):
    for j in range(column):
        result[i][j] = matrix_a[i][j]+matrix_b[i][j]

print("The Sum of Above two Matrices is : ")
for r in result:
    print(r)

Enter the Number of rows : 2
Enter the Number of Columns: 2
Enter the elements of First Matrix:
10
15
2
5
First Matrix is: 
[10, 15]
[2, 5]
Enter the elements of Second Matrix:
20
15
30
55
[20, 15]
[30, 55]
The Sum of Above two Matrices is : 
[30, 30]
[32, 60]


2.Write a Python Program to Multiply Two Matrices?

In [5]:
rows = int(input("Enter the Number of rows : " ))
column = int(input("Enter the Number of Columns: "))

print("Enter the elements of First Matrix:")
matrix_a= [[int(input()) for i in range(column)] for i in range(rows)]
print("First Matrix is: ")
for n in matrix_a:
    print(n)

print("Enter the elements of Second Matrix:")
matrix_b= [[int(input()) for i in range(column)] for i in range(rows)]
print("Second Matrix is: ")
for n in matrix_b:
    print(n)
    
result=[[0 for i in range(column)] for i in range(rows)]


for i in range(len(matrix_a)):
    for j in range(len(matrix_b)):
        for k in range(len(matrix_b)):
             result[i][j] += matrix_a[i][k] * matrix_b[k][j]
                
print("Multiplication of matrix1 and matrix2 is: ")
for r in result:
    print(r)

Enter the Number of rows : 3
Enter the Number of Columns: 3
Enter the elements of First Matrix:
1
2
5
6
4
7
8
2
10
First Matrix is: 
[1, 2, 5]
[6, 4, 7]
[8, 2, 10]
Enter the elements of Second Matrix:
12
5
3
4
13
15
5
8
7
Second Matrix is: 
[12, 5, 3]
[4, 13, 15]
[5, 8, 7]
Multiplication of matrix1 and matrix2 is: 
[45, 71, 68]
[123, 138, 127]
[154, 146, 124]


3.Write a Python Program to Transpose a Matrix?

In [6]:
import numpy as np
A = np.array([ [1,2,3], [4,5,6], [7,8,9]])
print(A)
print("Transpose of matrix:")
print(A.transpose())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of matrix:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


4.Write a Python Program to Sort Words in Alphabetic Order?

In [12]:
string = input("Enter a string: ")

# breakdown the string into a list of words
words = [word.lower() for word in string.split()]

# sort the list
words.sort()

print("\nThe sorted words are:")
print(' '.join(words))


Enter a string: the Quick brown fox jumPs over the lazY Dog

The sorted words are:
brown dog fox jumps lazy over quick the the


5.Write a Python Program to Remove Punctuation From a String?

In [15]:
# define punctuation
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

# take input from the user
string = input("Enter a string: ")

# remove punctuation from the string
no_punct = ""
for char in string:
    if char not in punctuations:
        no_punct = no_punct + char

# display the unpunctuated string
print(no_punct)

Enter a string: Hello!! welcome to ineuron!!
Hello welcome to ineuron
